### ISSUE TITLE
underlying 3rd party connection status awareness

### ISSUE THREAD

**Issue by kfatehi** [AndrewJDR/matrix-puppet-bridge#3]
when i send a message, i dont know 100% that it's going to successfully send. for all we know, the underlying connection is broken and the message wont be delivered to the 3rd party.

we need a way to show feedback of whether or not the message was delivered to the 3rd party.

we also need a way to know if the bridge itself is working or not (i.e. am i likely going to miss messages at this time?)

one solution is to have a bridge bot room that shows this kind of general status. e.g.

"third party client connected! you will receive messages from the third party service!"

"third party client disconnected! you will NOT receive messages from the third party service!"

"third party client reconnected! you will receive messages from the third party service!"

we can use this for message delivery issues, but it's probably better to do that in the room in which the message was sent.

e.g.  in a chat:

"Notice: Message failed to deliver to third party."

with that information, a few redelivery strategies can be setup, like a !retry command or whatever, but for now we just need awareness.

**Comment by AndrewJDR** [comment]
3a4c1004e1 Adds a sendThirdPartyProtocolStatusMsg method that you can call to send protocol status messages to the bridge owner. It will handle creating the room, joining the owner, joining the bot, and sending the message. Some notes:
Should probably have had an argument to the method to wrap the message inside a `<code><pre>` or not. Currently it just always wraps in a `<code><pre>`.
